//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odradeno
    {
        public int OdradenoId { get; set; }
        public int UserId { get; set; }
        public int SatnicaId { get; set; }
        public System.DateTime Dan { get; set; }
        public int Sati { get; set; }
    
        public virtual Satnica Satnica { get; set; }
        public virtual User User { get; set; }
    }
}
